# Generated by Django 5.2.7 on 2025-11-30 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosYoutube',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criacao')),
                ('id_dados', models.AutoField(primary_key=True, serialize=False)),
                ('autor_link', models.CharField(max_length=255)),
                ('titulo_link', models.CharField(max_length=255)),
                ('duracao', models.IntegerField()),
                ('miniatura', models.CharField(max_length=255)),
                ('link_tube', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoviesSalvasServidor',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criacao')),
                ('id_movies', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255, null=True)),
                ('path_arquivo', models.CharField(max_length=255, null=True)),
                ('duracao_midia', models.IntegerField()),
                ('path_miniatura', models.FileField(max_length=255, upload_to='miniaturas/')),
                ('dados_youtube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreYoutube.dadosyoutube')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicsSalvasServidor',
            fields=[
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='data_criacao')),
                ('id_music', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255, null=True)),
                ('path_arquivo', models.CharField(max_length=255, null=True)),
                ('duracao_midia', models.IntegerField()),
                ('path_miniatura', models.FileField(max_length=255, upload_to='miniaturas/')),
                ('dados_youtube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreYoutube.dadosyoutube')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
